blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
# from django.contrib.auth import views
from . import views

app_name = 'blog'
urlpatterns = [
    # path("articles_check/", views.articles_display, name="articles_display"),

    path('', views.homepage_view, name='homepage_view'),
    path('blogs/', views.blog_index, name="blog_index"),
    path('search_result/', views.blog_index_search, name="blog_index_search"),
    path('search_results/', views.blog_index_searched, name="blog_index_searched"),
    path('popular/', views.popular_views, name="popular_views"),
    path("new/", views.blog, name="blog"),
    path("contact-us/", views.blog_contact, name="blog_contact"),
    path("<slug:slug>/", views.blog_detail, name="blog_detail"),
    path("legal/<slug:slug>/", views.blog_detail_legal, name="blog_detail_legal"),
    path("pending/<slug:slug>/", views.pending_blog_detail, name="pending_blog_detail"),
    path("articles_list/<category>/", views.blog_category, name="blog_category"),
    path("tags_list/<tag>/", views.blog_tag, name="blog_tag"),
    path("dashboard/authors/", views.dashboard_authors, name="dashboard_authors"),
    path("dashboard/pending/", views.dashboard_pending_post, name="dashboard_pending_post"),
    path("author/<author>/", views.blog_author, name="blog_author"),
    path("dashboard/<author>/", views.dashboard_home, name="dashboard_home"),
    path("dashboard/<author>/messaging", views.dashboard_messaging, name="dashboard_messaging"),
    path("dashboard/<author>/message/<uidb64>/", views.dashboard_opened_message, name="dashboard_opened_message"),
    path("dashboard/<author>/request", views.dashboard_request, name="dashboard_request"),
    path("dashboard/<author>/collaburation", views.dashboard_collaburation, name="dashboard_collaburation"),
    path("dashboard/<author>/new", views.dashboard_add_post, name="dashboard_add_post"),
    path("dashboard/<author>/posts", views.dashboard_view_post, name="dashboard_view_post"),
    path("dashboard/<author>/edit", views.dashboard_view_post_edit, name="dashboard_view_post_edit"),
    path("dashboard/<author>/posts-collaburation", views.dashboard_collabutation_view, name="dashboard_collabutation_view"),
    path("dashboard/<author>/profile", views.dashboard_profile, name="dashboard_profile"),
    path("dashboard/<slug:slug>/edit/", views.edit_blog, name="edit_blog"), 
    path("dashboard/collaburation/<slug:slug>/edit/", views.collaburation_edit_blog, name="collaburation_edit_blog"), 
    path("<slug:slug>/delete/", views.delete_blog, name='delete_blog'), 
    path("ajax/addnewsletter/", views.add_newsletter_email, name='add_newsletter_email'),
    path("ajax/add_category_request/", views.add_category_request, name='add_category_request'),
    path("ajax/request_key/", views.request_key, name='request_key'),
    path("ajax/verfiy_post_collaburation/", views.verfiy_post_collaburation, name='verfiy_post_collaburation'),
    path("ajax/collaburation_handshake/", views.collaburation_handshake, name='collaburation_handshake'),
    path("ajax/request_category/", views.request_category, name='request_category'),
    path("ajax/user_send_message/", views.user_send_message, name='user_send_message'),
    # path("ajax/user_send_message_other/", views.user_send_message_other, name='user_send_message_other'),
    # path("ajax/user_send_message_admin/", views.user_send_message_admin, name='user_send_message_admin'),
    path("ajax/add_category/", views.add_category, name='add_category'),
    path("ajax/verify_post/", views.add_post_request, name='add_post_request'),
    # path("articles/<slug:slug>/", views.category_archive, name='category_archive'),
    # path("<int:pk>/", views.blog_detail, name="blog_detail"),
    # path("<int:pk>/edit/", views.edit_blog, name="edit_blog"),
    # path("<int:pk>/delete/", views.delete_blog, name='delete_blog'),
    # path("add_comment/<int:pk>/", views.add_comment, name="add_comment"),
] 

mebbscorner/urls.py
from django.contrib import admin
from django.urls import path, include
from .tasks import notify_user
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import StaticSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    # 'article': PostSitemap,
    'static': StaticSitemap
    }

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('blog.urls',namespace="blog")),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path("accounts/", include('accounts.urls', namespace="accounts")),
    # path('accounts/', include('django.contrib.auth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 
# notify_user(repeat=10, repeat_until=None)

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
# from taggit.managers import TaggableManager
User = settings.AUTH_USER_MODEL
from .select_options import COUNTRY, REQUEST_DEFAULT, published_choice_admin, published_choice_staff
from io import StringIO
from html.parser import HTMLParser


class Tags(models.Model):
    name = models.CharField(max_length=20, unique=True)
    added_by = models.ForeignKey(User, null=True, on_delete = models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    added_by = models.ForeignKey(User, null=True, on_delete = models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
  
    def __str__(self):
        return self.name
    
    # def get_absolute_url(self):
    #     return reverse('category_archive', kwargs={'slug': self.slug})


class Post(models.Model):
    author = models.ForeignKey(User, null = True, on_delete = models.SET_NULL, related_name='publisher') 
    title = models.CharField(max_length=30, verbose_name="Post title")
    slug = models.SlugField(unique=True, max_length=100, null=True)
    body = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)
    cover_image = models.ImageField(default='teadefault.jpg', upload_to='images/') 
    last_modified = models.DateTimeField(auto_now=True, blank=True)
    published_flag = models.BooleanField(null=True, default=False)
    status = models.CharField(max_length=7, null=True)
    number_of_comments = models.IntegerField(null=True)
    favorite = models.BooleanField(null=True)
    read_duration = models.IntegerField(null=True, default=3)
    number_of_views = models.IntegerField(null=True, default=0)
    new_tag = models.ManyToManyField('Tags', related_name='tag')
    categories = models.ManyToManyField('Category', related_name='posts')
    approved_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='approval_officer' )

    def __str__(self):
        return self.title 

    def strip_tags(self):
        s = MLStripper()
        s.feed(self.body)
        return s.get_data()

    def sttt(self):
        return self.title 
        
    # def get_absolute_url(self):
    #     return reverse('blog:blog_detail', args = [str(self.slug)])
        # return (kwargs={'slug': self.slug})
        # return f'/{self.slug}'

class MLStripper(HTMLParser):
    def __init__(self):
        super().__init__()
        self.reset()
        self.strict = False
        self.convert_charrefs= True
        self.text = StringIO()
    def handle_data(self, d):
        self.text.write(d)
    def get_data(self):
        return self.text.getvalue()
    
class Post_views(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postview')
    ip = models.CharField(max_length=40)
    session = models.CharField(max_length=40, null=True)
    created = models.DateTimeField(auto_now_add=True)
    
class Post_liked(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postliked')
    ip = models.CharField(max_length=40)
    session = models.CharField(max_length=40, null=True)
    created = models.DateTimeField(auto_now_add=True)

class Follower_list(models.Model):
    user_followed = models.ForeignKey(User, on_delete=models.CASCADE, related_name='main_user')
    followers = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower_user')

class Comment(models.Model):
    name = models.CharField(max_length=80)#, default="Anonymous")
    url = models.URLField(max_length=80, null=True)#, default="Anonymous")
    email = models.EmailField(max_length=200)
    body = models.CharField(max_length=250, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    author_voice = models.BooleanField(null=True, default=False)
    co_author_voice = models.BooleanField(null=True, default=False)
    active_writer = models.BooleanField(null=True, default=False)
    active_writer_inst = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    active = models.BooleanField(default=True)
    parent = models.ForeignKey('self',on_delete=models.CASCADE, null=True, blank=True, related_name='replies')

    # class Meta:
    #     # sort comments in chronological order by default
    #     ordering = ("-created_on")

    def __str__(self):
        return 'Comment by {}'.format(self.name)

class Newsletter_subcribers(models.Model):
    email = models.EmailField(max_length=200,unique=True)
    verified = models.BooleanField(null=True, default=False)
    created_on = models.DateTimeField(auto_now_add=True)

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    number_of_post = models.IntegerField(null=True)
    number_of_views = models.IntegerField(null=True, default=0)
    profile_complete = models.BooleanField(null=True, default=False)
    birth_date = models.DateField(null=True , blank=True)
    bio = models.TextField(max_length=200 , null=True, blank=True)
    sex = models.CharField(max_length=6 , null=True, blank=True)
    location = models.CharField(max_length=30 , choices=COUNTRY, null=True, blank=True)
    cover_image = models.ImageField(default='default_image.jpg', null=True, upload_to='profile/images/') 
    linkedin = models.URLField(max_length=80, null=True)
    twitter = models.URLField(max_length=80, null=True)
    github = models.URLField(max_length=80, null=True)
    whatsapp = models.URLField(null=True)
    visibility = models.BooleanField(null=True, default=False)

    def __str__(self):
        return str(self.user)


class Collaburating_author(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    key = models.CharField(max_length=30, unique=True)
    created_on = models.DateField(auto_now_add=True)
    approved_on = models.DateField(null=True)
    status = models.BooleanField(default=False, null=True)
    requested_status = models.BooleanField(default=True, null=True)
    request_accepted = models.BooleanField(default=False, null=True)
    author_in_request = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='collaburatee')
    requested_author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='collaburation_requested_by')
    approved_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='collaburation_approved_by')
    
    def __str__(self):
        return str(self.key)

class Post_history(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null = True, on_delete = models.SET_NULL)
    created_on = models.DateField(null=True, auto_now_add=True)
    description = models.CharField(null=True, max_length=30)
    state = models.CharField(null=True, max_length=30)

class Contact_us(models.Model):
    first_name = models.CharField(max_length=15 , null=True)
    last_name = models.CharField(max_length=15, null=True)
    email = models.EmailField(max_length=20, null=True)
    phone_number = models.IntegerField(null=True)
    messages = models.CharField(max_length=70 , null=True)

class Author_request(models.Model):
    username = models.ForeignKey(User, null = True, on_delete = models.SET_NULL, related_name='requst_publisher') 
    title = models.CharField(unique=True, max_length=30 , null=True)
    encodededpk = models.CharField(unique=True, max_length=5, null=True)
    weight = models.CharField(max_length=10, default='Heavy')
    message = models.CharField(unique=True, max_length=100 , null=True)
    markas_read = models.BooleanField(default=False, null=True)
    created_on = models.DateField(auto_now_add=True, null=True)
    modified_on = models.DateField(auto_now=True, null=True)
    message_to = models.ForeignKey(User, null=True, on_delete = models.SET_NULL) 
    approved_by = models.ForeignKey(User, null = True, on_delete = models.SET_NULL, related_name='requst_approval') 

class Author_request_category(models.Model):
    username = models.ForeignKey(User, null = True, on_delete = models.SET_NULL, related_name='requst_cat_publisher') 
    options = models.CharField(max_length=20 , null=True, default='Request Category')
    category = models.CharField(unique=True, max_length=30 , null=True)
    status = models.CharField(max_length=30 , null=True)
    created_on = models.DateField(auto_now_add=True, null=True)
    approved = models.BooleanField(default=False, null=True)
    modified_on = models.DateField(null=True)
    approved_by = models.ForeignKey(User, null=True, on_delete = models.SET_NULL, related_name='requst_cat_approval') 

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

blog/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block head_title %} {{ user.last_name }}'s Dashboard {% endblock %}


{% block page_content %}
<div class="site-section py-0">
    <div class="site-section">
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-secondary sidebar sidebar-dark accordion pl-2" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center"
                    href="{% url 'blog:dashboard_home' user.username %}">
                    {% if user.is_superuser %}
                    <div class="sidebar-brand-text mx-3"> Administrator</div>
                    {% else %}
                    <div class="sidebar-brand-text mx-3"> Writer</div>
                    {% endif %}
                </a>

                <!-- Divider -->
                <hr class="sidebar-divider my-0">

                <!-- Nav Item - Dashboard -->
                {% if bt_highlighted_home %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}
                    <a class="nav-link" href="{% url 'blog:dashboard_home' user.username %}">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span></a>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Author's Louge
                </div>

                {% if bt_highlighted_add_post %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}
                    <a class="nav-link" href="{% url 'blog:dashboard_add_post' user.username %}">
                        <i class="fa fa-plus"></i>
                        <span>Add Post</span></a>
                </li>

                {% if bt_highlighted_edit %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}
                    <a class="nav-link" href="{% url 'blog:dashboard_view_post_edit' user.username %}">
                        <i class="fas fa-fw fa-edit"></i>
                        <span>Edit</span></a>
                </li>

                {% if bt_highlighted_view_post %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}
                    <a class="nav-link" href="{% url 'blog:dashboard_view_post' user.username %}">
                        <i class="fa fa-eye"></i>
                        <span>View Post</span></a>
                </li>


                {% if bt_highlighted_profile %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}

                    <a class="nav-link" href="{% url 'blog:dashboard_profile' user.username %}">
                        <i class="fas fa-fw fa-user"></i>
                        <span>Profile</span></a>
                </li>
                {% if user.is_superuser is True %}
                {% if bt_highlighted_pending %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}

                    <a class="nav-link" href="{% url 'blog:dashboard_pending_post' %}">
                        <i class="fas fa-fw fa-book"></i>
                        <span>Pending Post</span></a>
                </li>
                {% endif %}

                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Others
                </div>

                {% if bt_highlighted_messaging %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}

                    <a class="nav-link" href="{% url 'blog:dashboard_messaging' user.username %}">
                        <i class="fas fa-fw flaticon-email"></i>
                        <span>Messaging</span></a>
                </li>


                {% if bt_highlighted_dashboard_authors %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}

                    <a class="nav-link" href="{% url 'blog:dashboard_authors' %}">
                        <i class="fas fa-fw fa-users"></i>
                        <span>Hall of Writers</span></a>
                </li>
                {% if bt_highlighted_dashboard_collabutation_view %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}

                    <a class="nav-link" href="{% url 'blog:dashboard_collabutation_view' user.username %}">
                        <i class="fas fa-fw fa-book"></i>
                        <span>Collaburate</span></a>
                </li>

                {% if bt_highlighted_dashboard_request %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}

                    <a class="nav-link" href="{% url 'blog:dashboard_request' user.username %}">
                        <i class="fas fa-fw fa-question"></i>
                        <span>Request</span></a>
                </li>

                <hr class="sidebar-divider d-none d-md-block">

                <!-- Sidebar Toggler (Sidebar) -->
                <div class="text-center d-none d-md-inline">
                    <button class="rounded-circle border-0" id="sidebarToggle"></button>
                </div>

            </ul>
            <!-- End of Sidebar -->

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    <!-- Topbar -->
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                        <!-- Sidebar Toggle (Topbar) -->
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>

                        <!-- Topbar Navbar -->
                        <ul class="navbar-nav ml-auto">

                            <li class="nav-item dropdown no-arrow mx-1">
                                <a class="nav-link dropdown-toggle"
                                    href="{% url 'blog:dashboard_request' user.username %}" id="alertsDropdown"
                                    role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-bell fa-fw"></i>
                                    <span class="badge badge-danger badge-counter"></span>
                                </a>
                            </li>

                            <!-- Nav Item - Messages -->
                            <li class="nav-item dropdown no-arrow mx-1">
                                <a class="nav-link dropdown-toggle"
                                    href="{% url 'blog:dashboard_messaging' user.username %}" id="messagesDropdown"
                                    role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-envelope fa-fw"></i>
                                    <!-- Counter - Messages -->
                                    <span class="badge badge-danger badge-counter"></span>
                                </a>
                            </li>

                            <!-- <div class="topbar-divider d-none d-sm-block"></div> -->

                            <!-- Nav Item - User Information -->

                        </ul>

                    </nav>
                    <!-- End of Topbar -->

                    <!-- Begin Page Content -->
                    {% block dashboard %}

                    {% endblock %}
                    <!-- /.container-fluid -->

                </div>
                <!-- End of Main Content -->
            </div>
            <!-- End of Content Wrapper -->
        </div>
        <!-- End of Page Wrapper -->
        <!-- Scroll to Top Button-->
        </dir>
    </div>
</div>
{% endblock %}

blog/templates/dashboard_profile.html
{% extends "dashboard.html" %}
{% load static %}
{% block head_title %} {{ user.last_name }}'s Dashboard {% endblock %}

{% block dashboard %}

<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="section-title mb-5">
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Profile</h1>
                </div>
                <div class="col-md-9 alert alert-warning alert-dismissible fade show" role="alert">
                    <strong> Attention! </strong> Please make sure all mark as required field are updated else all
                    post will not be published
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="col-md-9 alert alert-success alert-dismissible fade show" role="alert">
                    Mark as required field are indicated by<strong> *</strong> 
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form modelAttribute="api" method="POST" class="register-form" id="register-form"
                    enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_username"><i class="zmdi"></i>*</label>
                            {{ form.username }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="first_name"><i class="zmdi"></i>*</label>
                            {{ form.first_name }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_last_name"><i class="zmdi"></i>*</label>
                            {{ form.last_name }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_email"><i class="zmdi zmdi-email">*</i></label>
                            {{ form.email }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_location"><i class="zmdi"></i>* Select your countries</label>
                            {{ form_two.location }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_birth_date"><i class="zmdi"></i></label>
                            {{ form_two.birth_date }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-3 form-group">
                            <div class="form-check">
                                {{ form_two.remove_photo }}
                                <label class="form-check-label" for="id_remove_photo">
                                    Remove Image
                                </label>
                            </div>
                            <label for="id_cover_image"><i class="zmdi"></i></label>
                            {{ form_two.cover_image }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_bio"><i class="zmdi"></i>*</label>
                            {{ form_two.bio }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_sex"></label>
                            {{ form_two.sex }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_linkedin"><i class="zmdi"></i></label>
                            {{ form_two.linkedin }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_twitter"><i class="zmdi"></i></label>
                            {{ form_two.twitter }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_github"><i class="zmdi"></i></label>
                            {{ form_two.github }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="id_whatsapp"><i class="zmdi"></i></label>
                            {{ form_two.whatsapp }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="form-check">
                            {{ form_two.visibility }}
                            <label class="form-check-label" for="id_visibility">
                                Show Social Platforms
                            </label>
                        </div>
                    </div>


                    <div class="col-3 form-group">
                        <input type="submit" name="signup" id="signup" class="btn btn-primary py-3 px-5"
                            value="Update" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
{% endblock %}

{% block javascript %}

{% if messages %}
{% for message in messages %}
<script>
    var tag_alert = '{{ message.tags }}';
    if (tag_alert == 'alert-success') {
        tag_alert = 'success';
    }
    if (tag_alert == 'alert-danger') {
        tag_alert = 'error';
    }
    Swal.fire({
        position: 'top-end',
        icon: tag_alert,
        title: '{{ message }}',
        showConfirmButton: false,
        timer: 1500
    })
</script>
{% endfor %}
{% endif %}

{% endblock javascript %}