accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout_view, name="logout_view"),    
    path('ajax/validate_username/', views.validate_username, name='validate_username'),
    path('ajax/password_strenght/', views.password_strenght, name='password_strenght'),
    path('ajax/validate_username_signup/', views.validate_username_signup, name='validate_username_signup'),
    path('ajax/validate_email_signup/', views.validate_email_signup, name='validate_email_signup'),
    path("reset_password/", views.password_reset_request, name="password_reset"),
    path("verify_account/", views.verify_account, name="verify_account"),
    path('reset_password_sent', views.custom_password_reset_done, name='custom_password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('password_reset_complete/', views.custom_password_reset_done_complete, name='custom_password_reset_done_complete'),
    path('email_verification_sent/', views.email_verification_sent, name='email_verification_sent'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount, name='ActivateAccount'),
    # path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
# from django.contrib.auth import views
from . import views

app_name = 'blog'
urlpatterns = [
    # path("articles_check/", views.articles_display, name="articles_display"),

    path('', views.homepage_view, name='homepage_view'),
    path('blogs/', views.blog_index, name="blog_index"),
    path('search_result/', views.blog_index_search, name="blog_index_search"),
    path('search_results/', views.blog_index_searched, name="blog_index_searched"),
    path('popular/', views.popular_views, name="popular_views"),
    path("new/", views.blog, name="blog"),
    path("contact-us/", views.blog_contact, name="blog_contact"),
    path("<slug:slug>/", views.blog_detail, name="blog_detail"),
    path("legal/<slug:slug>/", views.blog_detail_legal, name="blog_detail_legal"),
    path("pending/<slug:slug>/", views.pending_blog_detail, name="pending_blog_detail"),
    path("articles_list/<category>/", views.blog_category, name="blog_category"),
    path("tags_list/<tag>/", views.blog_tag, name="blog_tag"),
    path("dashboard/authors/", views.dashboard_authors, name="dashboard_authors"),
    path("dashboard/pending/", views.dashboard_pending_post, name="dashboard_pending_post"),
    path("author/<author>/", views.blog_author, name="blog_author"),
    path("dashboard/<author>/", views.dashboard_home, name="dashboard_home"),
    path("dashboard/<author>/messaging", views.dashboard_messaging, name="dashboard_messaging"),
    path("dashboard/<author>/message/<uidb64>/", views.dashboard_opened_message, name="dashboard_opened_message"),
    path("dashboard/<author>/request", views.dashboard_request, name="dashboard_request"),
    path("dashboard/<author>/collaburation", views.dashboard_collaburation, name="dashboard_collaburation"),
    path("dashboard/<author>/new", views.dashboard_add_post, name="dashboard_add_post"),
    path("dashboard/<author>/posts", views.dashboard_view_post, name="dashboard_view_post"),
    path("dashboard/<author>/edit", views.dashboard_view_post_edit, name="dashboard_view_post_edit"),
    path("dashboard/<author>/posts-collaburation", views.dashboard_collabutation_view, name="dashboard_collabutation_view"),
    path("dashboard/<author>/profile", views.dashboard_profile, name="dashboard_profile"),
    path("dashboard/<slug:slug>/edit/", views.edit_blog, name="edit_blog"), 
    path("dashboard/collaburation/<slug:slug>/edit/", views.collaburation_edit_blog, name="collaburation_edit_blog"), 
    path("<slug:slug>/delete/", views.delete_blog, name='delete_blog'), 
    path("ajax/addnewsletter/", views.add_newsletter_email, name='add_newsletter_email'),
    path("ajax/add_category_request/", views.add_category_request, name='add_category_request'),
    path("ajax/request_key/", views.request_key, name='request_key'),
    path("ajax/verfiy_post_collaburation/", views.verfiy_post_collaburation, name='verfiy_post_collaburation'),
    path("ajax/collaburation_handshake/", views.collaburation_handshake, name='collaburation_handshake'),
    path("ajax/request_category/", views.request_category, name='request_category'),
    path("ajax/user_send_message/", views.user_send_message, name='user_send_message'),
    # path("ajax/user_send_message_other/", views.user_send_message_other, name='user_send_message_other'),
    # path("ajax/user_send_message_admin/", views.user_send_message_admin, name='user_send_message_admin'),
    path("ajax/add_category/", views.add_category, name='add_category'),
    path("ajax/verify_post/", views.add_post_request, name='add_post_request'),
    # path("articles/<slug:slug>/", views.category_archive, name='category_archive'),
    # path("<int:pk>/", views.blog_detail, name="blog_detail"),
    # path("<int:pk>/edit/", views.edit_blog, name="edit_blog"),
    # path("<int:pk>/delete/", views.delete_blog, name='delete_blog'),
    # path("add_comment/<int:pk>/", views.add_comment, name="add_comment"),
] 

mebbscorner/urls.py
from django.contrib import admin
from django.urls import path, include
from .tasks import notify_user
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import StaticSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    # 'article': PostSitemap,
    'static': StaticSitemap
    }

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('blog.urls',namespace="blog")),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path("accounts/", include('accounts.urls', namespace="accounts")),
    # path('accounts/', include('django.contrib.auth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 
# notify_user(repeat=10, repeat_until=None)

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import (login as auth_login,  authenticate, logout)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.http import JsonResponse
import re
import string
import hashlib
from datetime import datetime
import time 

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from .tokens import account_activation_token
from django.views.generic import View, UpdateView
from django.urls import reverse_lazy
from django.contrib.sites.shortcuts import get_current_site

from django.shortcuts import render, get_object_or_404, redirect
from blog.forms import CommentForm, PostForms2
from .forms import PasswordResetForm, PasswordResetConfirmViewForm
from blog.models import Post, Comment, Category, Tags, Profile


def login(request):
    if request.user.is_authenticated:
        messages.error(request,'Please logout first')
        return redirect('blog:dashboard_home', author=request.user)
    else:
        if request.method == 'POST':
            username = request.POST['your_name']
            raw_password = request.POST['your_pass']
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                check_mail = Profile.objects.get(user=user).email_confirmed
                if check_mail is False:
                    messages.error(request, 'User email is not verified, Please check email for activation link')
                elif user.is_active is False:
                    messages.error(request, 'User account in not activated')
                else:
                    auth_login(request, user)
                    messages.success(request, "Logged in")
                    return redirect('blog:dashboard_home', author=user)
            else:
                messages.error(request, 'Invalid Password or account in not activated')
        else:
            pass
    # print(urlsafe_base64_encode(force_bytes(request.user.pk)))
    # print(default_token_generator.make_token(request.user))
    return render(request, 'login.html', {"bt_highlighte_signing": True})


def signup(request):
    if request.method == 'POST':
        username = request.POST['name']
        raw_password = request.POST['pass']
        email_address = request.POST['email']
        _available = User.objects.filter(username__iexact=username).exists() | User.objects.filter(email__iexact=email_address).exists() 
        if raw_password == request.POST['re_pass'] and _available == False:
            if _available == False:
                user = User.objects.create_user(
                    username, 
                    email_address,
                    raw_password
                )
                user.first_name = request.POST['first_name']
                user.last_name = request.POST['last_name']
                user.is_active = False
                no_user = User.objects.all().count()
                if no_user == 0:
                    user.is_superuser = True
                user.save()

                subject = 'Activate Your TTL Account'
                email_template_name = "validate_email.txt"
                c = {
                    "email":user.email,
                    'domain':get_current_site(request),
                    'site_name': 'Website',
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
                    'token': default_token_generator.make_token(user),
                    'protocol': 'http',
                    }
                email = render_to_string(email_template_name, c)
                try:
                    send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                    messages.success(request, ('Please Confirm your email to complete registration.'))
                    corespondent = redirect("accounts:email_verification_sent")
                    srt2hash = str(datetime.now()) + 'Engaged'
                    key = hashlib.md5(srt2hash.encode()).hexdigest()
                    corespondent.set_cookie('TTL_EV', key , max_age=7200)
                    return corespondent

                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                # auth_login(request, user)
                # messages.success(request, "Your account has been successfully created")
            else:
                messages.error(request, "Username is unavaliable")
    return render(request, 'signup.html')

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Logged out")
        return HttpResponseRedirect("/")

def verify_account(request):
    if request.method == 'POST':
        email_verified = None
        email = request.POST['email']
        user = User.objects.get(email=email)
        _check_email = Profile.objects.get(user=user)
        email_verified = _check_email.email_confirmed
        if email_verified is False or user.is_active is False:
            subject = 'Activate Your TTL Account'
            email_template_name = "validate_email.txt"
            c = {
                "email":user.email,
                'domain':get_current_site(request),
                'site_name': 'Website',
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user,
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
                }
            email = render_to_string(email_template_name, c)
            try:
                send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                messages.success(request, ('Please Confirm your email to complete registration.'))
                corespondent = redirect("accounts:email_verification_sent")
                srt2hash = str(datetime.now()) + 'Engaged'
                key = hashlib.md5(srt2hash.encode()).hexdigest()
                corespondent.set_cookie('TTL_EV', key , max_age=600)
                return corespondent

            except BadHeaderError:
                return HttpResponse('Invalid header found.')
    return render (request, 'verify_email.html')


def logout_to_login_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Logged out")
        return redirect('accounts:login')

def password_strenght(request):
    ajax_request = False
    message = ''
    if request.method == 'POST' and request.is_ajax:
        password = request.POST.get('password')
        if bool(re.match('((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&]).{8,30})', password)) == True:
            message = 'Password Strength 5/5'
            ajax_request = True
        elif bool(re.match('((\d*)([a-z]*)([A-Z]*).{8,30})', password)) == True:
            message = 'Password Strength 4/5'
            ajax_request = True
        elif bool(re.match('((\d*)([a-z]*).{8,30})', password)) == True:
            message = 'Password Strength 3/5'
            ajax_request = True
        elif bool(re.match('(([a-z]*).{8,30})', password)) == True:
            message = 'Password Strength 2/5'
            ajax_request = True
        elif bool(re.match('(([a-z]*).{1,30})', password)) == True:
            message = 'Password Strength 2/5'
            ajax_request = True
        else:
            message = 'Password Strength 1/5'
            ajax_request = True
    data = {
        'message' : message,
        'ajax_request': ajax_request
    }
    return JsonResponse(data)

def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)

def change_password_from_email(request):
    form = PasswordResetConfirmViewForm()
    context = {
        'form': form
    }
    return render (request, 'password_reset_confirm.html', context)

def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            try:
                data = password_reset_form.cleaned_data['email']
                associated_users = User.objects.filter(Q(email=data))
                if associated_users.exists():
                    for user in associated_users:
                        subject = "Password Reset Requested"
                        email_template_name = "password_reset_email.txt"
                        c = {
                            "email":user.email,
                            'domain':get_current_site(request),
                            'site_name': 'TTL',
                            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                            "user": user,
                            'token': default_token_generator.make_token(user),
                            'protocol': 'http',
                            }
                        email = render_to_string(email_template_name, c)
                        try:
                            send_mail(subject, email, 'support@thicktealover.com' , [user.email], fail_silently=False)
                        except BadHeaderError:

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}



{% block page_content %}
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title mb-5">
                    <h2>{% block head_title %} Login {% endblock %}</h2>
                </div>
                {% if messages %}
                {% for message in messages %}
                <div class=" col-md-6 alert {{ message.tags }} alert-dismissible fade show" role="alert">
                    <strong></strong><span class="icon-info-circle"></span></strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
                {% endif %}
                <form method="post" class="register-form" id="login-form" role="form"
                    action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="fname">Name</label>
                            <input type="text" id="fname" name="your_name" class="form-control form-control-lg"
                                placeholder="Username" autofocus=True>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="pass">Password</label>
                            <div class="input-group">
                                <input type="password" id="pass" name="your_pass"
                                    class="form-control form-control-lg pwd" placeholder="Password">
                                <span class="input-group-btn"> <button type="button"
                                        class="form-control form-control-lg btn btn-default reveal"> <span
                                            class="mx-1 icon-eye" id="password_symbol"></span> </button></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-2 form-group">
                            <a href="{% url 'accounts:password_reset' %}" class="password_reset">Having Issues Logging in
                        </div>
                        <div class="col-md-2 form-group">
                            </a> <a href="{% url 'accounts:verify_account' %}" class="verify_account"> Verify
                                Email</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3 form-group">
                            <button type="submit" value="Login" class="btn btn-primary py-3 px-5">Login</button>
                        </div>
                    </div>
                </form>
                <div class="form-group">
                    <a href="{% url 'accounts:signup' %}" class="signup-image-link">Create an account</a>
                </div>


            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% if messages %}
{% for message in messages %}
<script>
    var tag_alert = '{{ message.tags }}';
    if (tag_alert == 'alert-success') {
        tag_alert = 'success';
    }
    if (tag_alert == 'alert-danger') {
        tag_alert = 'error';
    }
    Swal.fire({
        position: 'top-end',
        icon: tag_alert,
        title: '{{ message }}',
        showConfirmButton: false,
        timer: 1500
    })
</script>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong> <span class="icon-info-circle-o"> </strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% endfor %}
{% endif %}

<script>
    // $("#fname").focus();
    $(".reveal").on('click', function () {
        var $pwd = $(".pwd");
        var $symbol = $("#password_symbol")
        if ($pwd.attr('type') === 'password') {
            $pwd.attr('type', 'text');
            $symbol.attr('class', 'mx-1 icon-visibility_off')
        }
        else {
            $pwd.attr('type', 'password');
            $symbol.attr('class', 'mx-1 icon-eye')
        }
    });
    $("#fname").change(function () {
        var username = $(this).val();

        $.ajax({
            url: '{% url "accounts:validate_username" %}',
            data: {
                'username': username
            },
            dataType: 'json',
            success: function (data) {
                console.log(data.is_taken);
                if (!data.is_taken) {
                    // alert("A user with this username already exists.");
                    Swal.fire({
                        position: 'top-end',
                        icon: 'error',
                        title: 'No match for username "' + username + '"',
                        showConfirmButton: false,
                        timer: 1500
                    })
                }
            }
        });
    });
        // console.log("Hello");
</script>
{% endblock javascript %}

accounts/templates/password_reset_complete.html
{% extends 'base.html' %}

{% load static %}
{% block page_content %}
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title mb-2">
                    <h2>
                        {% block head_title %}Password reset complete{% endblock %}
                    </h2>
                </div>
                <p>Your new password has been set. You can log in now on the <a href="{% url 'accounts:login' %}"><strong>Login</strong>
                        </a>page.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load static %}


{% block page_content %}
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title mb-5">
                    <h2>{% block head_title %} Sign Up {% endblock %}</h2>
                </div>
                <form method="POST" class="register-form" id="register-form">
                    {% csrf_token %}
                    {% if messages %}
                    {% for message in messages %}
                    <div class=" col-md-6 alert {{ message.tags }} alert-dismissible fade show" role="alert">
                        <strong></strong><span class="icon-info-circle"></span></strong> {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            <input type="text" name="name" id="name" required class="form-control form-control-lg"
                                placeholder="Your Username" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="first_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            <input type="text" name="first_name" id="first_name" required
                                class="form-control form-control-lg" placeholder="Your First Name" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="last_name"><i class="zmdi"></i></label>
                            <input type="text" name="last_name" id="first_name" required
                                class="form-control form-control-lg" placeholder="Your Last Name" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="email"><i class="zmdi zmdi-email"></i></label>
                            <input type="email" name="email" id="email" required class="form-control form-control-lg"
                                placeholder="Your Email" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                            <div class="input-group">
                                <input type="password" name="pass" id="pass" class="form-control form-control-lg"
                                    placeholder="Password" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                            <div class="input-group">
                                <input type="password" name="re_pass" id="re_pass" class="form-control form-control-lg"
                                    placeholder="Repeat your password" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" required />
                            <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all
                                statements in <a class="term-service"
                                    href="{% url 'blog:blog_detail_legal' slug='terms-of-service' %}">Terms of
                                    service</a></label>
                        </div>
                    </div>
                    <div class="col-3 form-group">
                        <input type="submit" name="signup" id="signup" class="btn btn-primary py-3 px-5"
                            value="Register" />
                    </div>
                </form>
                <div class="row">
                    <div class="col-6 form-group">
                        <a href="{% url 'accounts:login' %}" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}

{% if messages %}
{% for message in messages %}
<script>
    var tag_alert = '{{ message.tags }}';
    if (tag_alert == 'alert-success') {
        tag_alert = 'success';
    }
    if (tag_alert == 'alert-danger') {
        tag_alert = 'error';
    }
    Swal.fire({
        position: 'top-end',
        icon: tag_alert,
        title: '{{ message }}',
        showConfirmButton: false,
        timer: 1500
    })
</script>
{% endfor %}
{% endif %}

<script>
    $("#name").focus();
    $("#name").change(function () {
        var username = $(this).val();
        $.ajax({
            url: '{% url "accounts:validate_username_signup" %}',
            data: {
                'username': username
            },
            dataType: 'json',
            success: function (data) {
                if (data.user_is_taken) {
                    // alert("A user with this username already exists.");
                    Swal.fire({
                        position: 'top-end',
                        icon: 'error',
                        title: 'Name does exist',
                        showConfirmButton: false,
                        timer: 1500
                    })
                    $("#signup").attr("disabled", true);
                }
                else {
                    $('#signup').removeAttr("disabled");
                }


            }
        });
    });
    $("#email").change(function () {
        var email = $(this).val();
        $.ajax({
            url: '{% url "accounts:validate_email_signup" %}',
            data: {
                'email': email
            },
            dataType: 'json',
            success: function (data) {
                if (data.email_is_taken) {
                    // alert("A user with this username already exists.");
                    Swal.fire({
                        position: 'top-end',
                        icon: 'error',
                        title: 'Email does exist',
                        showConfirmButton: false,
                        timer: 2000
                    })
                    $("#signup").attr("disabled", true);
                }
                else {
                    $('#signup').removeAttr("disabled");
                }


            }
        });
    });
    $("#pass").change(function () {
        var password = $(this).val();
        $.ajax({
            type: 'POST',
            url: '{% url "accounts:password_strenght" %}',
            data: {
                'password': password,
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
            },
            dataType: 'json',
            success: function (data) {
                // alert("A user with this username already exists.");
                console.log(data.ajax_request);
                if (data.ajax_request) {
                    Swal.fire({
                        position: 'top-end',
                        icon: 'info',
                        title: data.message,
                        showConfirmButton: false,
                        timer: 1500
                    })
                }
            }
        });
    });
</script>
{% endblock javascript %}