accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout_view, name="logout_view"),    
    path('ajax/validate_username/', views.validate_username, name='validate_username'),
    path('ajax/password_strenght/', views.password_strenght, name='password_strenght'),
    path('ajax/validate_username_signup/', views.validate_username_signup, name='validate_username_signup'),
    path('ajax/validate_email_signup/', views.validate_email_signup, name='validate_email_signup'),
    path("reset_password/", views.password_reset_request, name="password_reset"),
    path("verify_account/", views.verify_account, name="verify_account"),
    path('reset_password_sent', views.custom_password_reset_done, name='custom_password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('password_reset_complete/', views.custom_password_reset_done_complete, name='custom_password_reset_done_complete'),
    path('email_verification_sent/', views.email_verification_sent, name='email_verification_sent'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount, name='ActivateAccount'),
    # path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
# from django.contrib.auth import views
from . import views

app_name = 'blog'
urlpatterns = [
    # path("articles_check/", views.articles_display, name="articles_display"),

    path('', views.homepage_view, name='homepage_view'),
    path('blogs/', views.blog_index, name="blog_index"),
    path('search_result/', views.blog_index_search, name="blog_index_search"),
    path('search_results/', views.blog_index_searched, name="blog_index_searched"),
    path('popular/', views.popular_views, name="popular_views"),
    path("new/", views.blog, name="blog"),
    path("contact-us/", views.blog_contact, name="blog_contact"),
    path("<slug:slug>/", views.blog_detail, name="blog_detail"),
    path("legal/<slug:slug>/", views.blog_detail_legal, name="blog_detail_legal"),
    path("pending/<slug:slug>/", views.pending_blog_detail, name="pending_blog_detail"),
    path("articles_list/<category>/", views.blog_category, name="blog_category"),
    path("tags_list/<tag>/", views.blog_tag, name="blog_tag"),
    path("dashboard/authors/", views.dashboard_authors, name="dashboard_authors"),
    path("dashboard/pending/", views.dashboard_pending_post, name="dashboard_pending_post"),
    path("author/<author>/", views.blog_author, name="blog_author"),
    path("dashboard/<author>/", views.dashboard_home, name="dashboard_home"),
    path("dashboard/<author>/messaging", views.dashboard_messaging, name="dashboard_messaging"),
    path("dashboard/<author>/message/<uidb64>/", views.dashboard_opened_message, name="dashboard_opened_message"),
    path("dashboard/<author>/request", views.dashboard_request, name="dashboard_request"),
    path("dashboard/<author>/collaburation", views.dashboard_collaburation, name="dashboard_collaburation"),
    path("dashboard/<author>/new", views.dashboard_add_post, name="dashboard_add_post"),
    path("dashboard/<author>/posts", views.dashboard_view_post, name="dashboard_view_post"),
    path("dashboard/<author>/edit", views.dashboard_view_post_edit, name="dashboard_view_post_edit"),
    path("dashboard/<author>/posts-collaburation", views.dashboard_collabutation_view, name="dashboard_collabutation_view"),
    path("dashboard/<author>/profile", views.dashboard_profile, name="dashboard_profile"),
    path("dashboard/<slug:slug>/edit/", views.edit_blog, name="edit_blog"), 
    path("dashboard/collaburation/<slug:slug>/edit/", views.collaburation_edit_blog, name="collaburation_edit_blog"), 
    path("<slug:slug>/delete/", views.delete_blog, name='delete_blog'), 
    path("ajax/addnewsletter/", views.add_newsletter_email, name='add_newsletter_email'),
    path("ajax/add_category_request/", views.add_category_request, name='add_category_request'),
    path("ajax/request_key/", views.request_key, name='request_key'),
    path("ajax/verfiy_post_collaburation/", views.verfiy_post_collaburation, name='verfiy_post_collaburation'),
    path("ajax/collaburation_handshake/", views.collaburation_handshake, name='collaburation_handshake'),
    path("ajax/request_category/", views.request_category, name='request_category'),
    path("ajax/user_send_message/", views.user_send_message, name='user_send_message'),
    # path("ajax/user_send_message_other/", views.user_send_message_other, name='user_send_message_other'),
    # path("ajax/user_send_message_admin/", views.user_send_message_admin, name='user_send_message_admin'),
    path("ajax/add_category/", views.add_category, name='add_category'),
    path("ajax/verify_post/", views.add_post_request, name='add_post_request'),
    # path("articles/<slug:slug>/", views.category_archive, name='category_archive'),
    # path("<int:pk>/", views.blog_detail, name="blog_detail"),
    # path("<int:pk>/edit/", views.edit_blog, name="edit_blog"),
    # path("<int:pk>/delete/", views.delete_blog, name='delete_blog'),
    # path("add_comment/<int:pk>/", views.add_comment, name="add_comment"),
] 

mebbscorner/urls.py
from django.contrib import admin
from django.urls import path, include
from .tasks import notify_user
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import StaticSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    # 'article': PostSitemap,
    'static': StaticSitemap
    }

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('blog.urls',namespace="blog")),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path("accounts/", include('accounts.urls', namespace="accounts")),
    # path('accounts/', include('django.contrib.auth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 
# notify_user(repeat=10, repeat_until=None)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block head_title %} {% endblock %}</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=B612+Mono|Cabin:400,700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'Bootstrap_Extra/css/bootstrap-select.css' %}">
  <link rel="stylesheet" href="{% static 'css/nav_tab.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/css/sb-admin-2.min.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link rel="shortcut icon" href="{% static 'favicon.ico' type='image/x-icon' %}">
  <link href="{% static 'css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">

</head>


<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <div class="site-wrap mb-2">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <div class="header-top">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12 col-lg-6 d-flex">
            <a href="{% url 'blog:homepage_view' %}" class="site-logo">
              THICK TEA LOVER
            </a>
            <a href="#" class="ml-auto d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                class="icon-menu h1"></span></a>
          </div>
            {% if user.is_authenticated %}
            <div class="col-12 col-lg-3 d-flex">
            <div class="bio-pic mr-3">
              <img src="{{ user.profile.cover_image.url  }}" alt="Profile Image" class="img-fluidid">
            </div>
            <div class="d-inline-block"> Welcome, <a
                href="{% url 'blog:dashboard_home' user.username %}">{{ user.get_full_name }}</a></div>
            </div>
            {% endif %}

              <form action="{% url 'blog:blog_index_search' %}" method="POST"
                class="col-12 col-lg-3 ml-auto align-items-center">
                {% csrf_token %}
                <div class="d-flex">
                  <input type="search" name="search_word" class="form-control" id="search_word"
                    placeholder="Search...">
                  <button type="submit" class="btn btn-secondary"><span class="icon-search"></span></button>
                </div>
              </form>
          </div>
          <div class="col-12 d-block d-lg-none text-right">
          <div class="col-12 col-lg-6 ml-auto d-flex">
          </div>
        </div>
      </div>

      <div class="site-navbar py-2 js-sticky-header site-navbar-target d-none pl-0 d-lg-block" role="banner">
        <div class="container">
          <div class="row">
            <div class="d-flex align-items-center">
              <div class="mr-auto">
                <nav class="site-navigation position-relative text-right" role="navigation">
                  <ul class="site-menu main-menu js-clone-nav mr-auto d-none pl-0 d-lg-block">
                    {% if bt_highlighted_home %}
                    <li class="active"><a href="{% url 'blog:homepage_view' %}" class="nav-link text-left">Home</a></li>
                    {% else %}
                    <li class="home"><a href="{% url 'blog:homepage_view' %}" class="nav-link text-left">Home</a></li>
                    {% endif %}
                    {% if bt_highlighted_index %}
                    <li class="active"><a href="{% url 'blog:blog_index' %}" class="nav-link text-left">Blog</a></li>
                    {% else %}
                    <li class="blog"><a href="{% url 'blog:blog_index' %}" class="nav-link text-left">Blog</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    {% if bt_highlighted_add_blog %}
                    <li class="active"><a href="{% url 'blog:dashboard_add_post' user.username %}"
                      class="nav-link text-left">Add Blog</a></li>
                    {% else %}
                    <li class="add_blog"><a href="{% url 'blog:dashboard_add_post' user.username %}"
                      class="nav-link text-left">Add Blog</a></li>
                    {% endif %}
                    {% if bt_highlighted_logout %}
                    <li class="active"><a href="javascript:;" class="nav-link text-left"
                    onclick="log_out()">Logout</a></li>
                    {% else %}
                    <li class="logged_out"><a href="javascript:;" class="nav-link text-left"
                      onclick="log_out()">Logout</a></li>
                    {% endif %}
                  {% else %}
                  {% if bt_highlighte_signing %}
                  <li class="active"><a href="{% url 'accounts:login' %}" class="nav-link text-left">Login/Signup</a></li>
                  {% else %}
                  <li class="login_signup"><a href="{% url 'accounts:login' %}" class="nav-link text-left">Login/Signup</a></li>
                  {% endif %}
                    {% endif %}
                    {% if bt_highlighte_contact %}
                    <li class="active"><a href="{% url 'blog:blog_contact' %}" class="nav-link text-left">Contact</a></li>
                    {% else %}
                    <li class="Contact"><a href="{% url 'blog:blog_contact' %}" class="nav-link text-left">Contact</a></li>
                    {% endif %}
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% block page_content %}
      {% endblock %}

      <div class="footer">
        <div class="container">


          <div class="row">
            <div class="col-12">
              <div class="copyright">
                <p>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  Copyright &copy;
                  <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
                  with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com"
                    target="_blank">Colorlib</a>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <div class="ml-md-auto top-social d-lg-inline-block">
                  <a href="https://www.facebook.com/thicktealover" class="d-inline-block p-3"><span
                      class="icon-facebook"></span></a>
                  <a href="https://www.twitter.com/thicktealover" class="d-inline-block p-3"><span
                      class="icon-twitter"></span></a>
                  <a href="https://www.instagram.com/thicktealover" class="d-inline-block p-3"><span
                      class="icon-instagram"></span></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


    </div>
    <!-- .site-wrap -->

    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
          stroke="#ff5e15" /></svg></div>

    <script src="{% static 'js/jquery-3.3.1.min.js'  %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js'  %}"></script>
    <script src="{% static 'js/jquery-ui.js'  %}"></script>
    <script src="{% static 'js/popper.min.js'  %}"></script>
    <script src="{% static 'Bootstrap_Extra/js/bootstrap-select.js' %}"></script>
    <script src="{% static 'Bootstrap_Extra/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js'  %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js'  %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js'  %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js'  %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js'  %}"></script>
    <script src="{% static 'js/aos.js'  %}"></script>
    <script src="{% static 'js/tagsinput.js'  %}"></script>
    <script src="{% static 'js/sweetalert2.all.min.js'  %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js'  %}"></script>
    <script src="{% static 'js/jquery.sticky.js'  %}"></script>
    <script src="{% static 'js/jquery.mb.YTPlayer.min.js'  %}"></script>
    <script src="{% static 'js/main.js'  %}"></script>
    <script src="{% static 'dashboard/js/sb-admin-2.min.js'  %}"></script>
    <script src="{% static 'dashboard/vendor/chart.js/Chart.min.js'  %}"></script>
    <script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js'  %}"></script>
    <script src="{% static 'dashboard/js/demo/chart-area-demo.js'  %}"></script>
    <script src="{% static 'dashboard/js/demo/chart-pie-demo.js'  %}"></script>
    <script src="{% static 'js/headroom.min.js'  %}"></script>

    {% block javascript %}
    {% endblock javascript %}

</body>


<script>
  function log_out() {
    Swal.fire({
      title: 'Logging out?',
      text: "You are just about to logout!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, Logout ASAP!'
    }).then((result) => {
      if (result.value) {
        window.location.href = "{% url 'accounts:logout_view' %}";
      }
    })
  }
</script>

</html>

templates/check.html
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> -->
<!-- <link rel="stylesheet" href="../static/css/bootstrap-select.css"> -->
<!-- <script src="../static/js/jquery-3.3.1.min.js"></script> -->
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/js/bootstrap-select.js"></script> -->
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> -->

<!-- <link rel="stylesheet" href="../static/Bootstrap_Extra/css/bootstrap.min.css">
<link rel="stylesheet" href="../static/css/bootstrap-select.css">
<script src="../static/js/jquery-3.3.1.min.js"></script>
<script src="../static/Bootstrap_Extra/js/bootstrap-select.js"></script>
<script src="../static/Bootstrap_Extra/js/bootstrap.min.js"></script> -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/css/bootstrap-select.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/js/bootstrap-select.min.js"></script>

<select class="selectpicker" multiple data-live-search="true">
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Relish</option>
</select>